- hosts: localhost
  gather_facts: no
  vars_files:
    - credentials.yml
    - ec2secrets.yml
  tasks:
    - name: Provisioning an EC2 instance
      ec2:
        assign_public_ip: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ubuntu_18.04_LTS
        instance_type: t2.micro
        instance_tags:
          # secret value encrypted with ansible-vault
          # vault-pass is "ansible-django"
          Name: "{{ instance_tags__name }}"
        # random id to keep playbook idempotent
        id: i-ko3a15s43iai
        image: ami-026c8acd92718196b
        region: us-east-1
        wait: yes
        vpc_subnet_id: subnet-6eaae561
        zone: us-east-1f
      register: ec2

    - name: Adding all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ec2hosts
      loop: "{{ ec2.instances }}"

- hosts: ec2hosts
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - credentials.yml
  tasks:
    - name: Waiting for system to become reachable
      wait_for_connection:

    - import_role:
        name: common
    - import_role:
        name: db
    - import_role:
        name: web
      vars:
        app_user: ubuntu
        repo_dir: /home/ubuntu/uwsgi-quickstart

    - name: Displaying completion message
      debug:
        msg: "View your app at {{ inventory_hostname }}:8080"
