- hosts: localhost
  gather_facts: False
  vars_files:
    - external_vars.yml
  tasks:
    - name: Provision an EC2 instance
      ec2:
        assign_public_ip: true
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: ubuntu_18.04_LTS
        instance_type: t2.micro
        instance_tags:
          Name: test_instance
        id: i-ko3a15s43iaa # random (to keep playbook idempotent)
        image: ami-026c8acd92718196b
        region: us-east-1
        wait: true
        vpc_subnet_id: subnet-6eaae561
        zone: us-east-1f
      register: ec2
    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ec2hosts
      loop: "{{ ec2.instances }}"
- hosts: ec2hosts
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars_files:
    - external_vars.yml
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
    - name: Install Postgres
      apt:
        name: "{{ packages }}"
        update_cache: true
      vars:
        packages:
          - python3-pip
          - python3-dev
          - python3-pkg-resources
          - python3-setuptools
          - libpq-dev
          - postgresql
          - postgresql-contrib
    - name: Install psycopg2
      pip:
        name: psycopg2
    - name: Create Postgres Database
      become: true
      become_user: postgres
      postgresql_db:
        name: test_db
    - name: Create Postgres User
      become: true
      become_user: postgres
      postgresql_user:
        db: test_db
        name: django
        password: password123
        priv: ALL
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: true
    - name: Make sure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: true
    - name: Generate SSH key
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa
        comment: ubuntu
        owner: ubuntu
        group: ubuntu
    - name: Read SSH public key to authorize
      shell: cat /home/ubuntu/.ssh/id_rsa.pub
      # registers RETURN value of shell play to ssh_pub_key variable
      register: ssh_pub_key
    - name: Authorize key with GitHub
      local_action:
        name: ansible-django-test
        module: github_key
        token: "{{ github_access_token }}"
        pubkey: "{{ ssh_pub_key.stdout }}"
    - name: Download app source code
      git:
        repo: "https://github.com/hankehly/uwsgi-quickstart.git"
        dest: /home/ubuntu/uwsgi-quickstart
