- hosts: tag_Name_test_instance
  remote_user: ubuntu
  become: no
  tasks:
    - name:
      debug:
        var: ansible_facts
    # database
    - name: Install Postgres
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - python3-pip
          - python3-dev
          - python3-pkg-resources
          - python3-setuptools
          - libpq-dev
          - postgresql
          - postgresql-contrib
    - name: Install psycopg2
      pip:
        name: psycopg2
      become: yes
      become_user: ubuntu
    - name: Create Postgres Database
      become: yes
      become_user: postgres
      postgresql_db:
        name: test_db
    - name: create postgres user
      postgresql_user:
        db: test_db
        name: test_user
        password: password123
        priv: all
    # web server
    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
    - name: make sure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
    # django app
    - name: Generate SSH key
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa
        comment: ubuntu
        owner: ubuntu
#    - name: download app source code from git
#      repo: 'https://github.com/hankehly/uwsgi-quickstart.git'
#      dest: /home/test_user
