- hosts: localhost
  gather_facts: no
  vars_files:
    - vars/aws.yml
    - vars/ec2secrets.yml
  tasks:
    - name: Querying AWS for EC2 instance list
      ec2_instance_facts:
        filters:
          "tag:Name": "{{ instance_tags__name }}"
      register: ec2_facts

    # TODO: Indexing here is not ideal
    - name: Terminating test EC2 instance
      ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids:
          - ec2_facts.instances[0].instance_id
        state: terminated
        wait: yes
      when: ec2_facts.instances|length == 1

    - name: Deleting EC2 keypair
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: ansible-django
        region: "{{ region }}"
        state: absent
        wait: yes

    - name: Deleting security group
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: "ansible-django"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        state: absent
