- name: Installing postgres
  apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-contrib
    update_cache: yes

- name: Installing psycopg2
  pip:
    name: psycopg2
    executable: /usr/bin/pip3

- name: Creating postgres db
  become: yes
  become_user: postgres
  postgresql_db:
    name: test_db

- name: Creating postgres db-user
  become: yes
  become_user: postgres
  postgresql_user:
    db: test_db
    name: django
    password: password123
    priv: ALL