- name: Installing nginx
  apt:
    name: nginx
    update_cache: yes

- name: Placing template nginx.conf to /etc/nginx/conf.d/uwsgiquickstart.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/uwsgiquickstart.conf
    mode: '0644'

- name: Generating SSH key
  openssh_keypair:
    path: "/home/{{ app_user }}/.ssh/id_rsa"
    comment: "{{ app_user }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Reading SSH public key to authorize
  command: "cat /home/{{ app_user }}/.ssh/id_rsa.pub"
  register: ssh_pub_key

- name: Authorizing key with GitHub
  github_key:
    name: ansible-django-test
    token: "{{ github_access_token }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
  delegate_to: localhost
  vars:
    ansible_python_interpreter: auto

- name: Downloading app source code
  git:
    repo: "https://github.com/hankehly/uwsgi-quickstart.git"
    dest: "{{ repo_dir }}"
    update: yes
    version: 1.0.0
    force: yes
  become: yes
  become_user: "{{ app_user }}"

- name: Installing poetry
  pip:
    name: poetry
    executable: /usr/bin/pip3

- name: Creating virtualenv
  command: python3 -m venv .venv
  args:
    chdir: "{{ repo_dir }}/django"
    creates: "{{ repo_dir }}/django/.venv"
  become: yes
  become_user: "{{ app_user }}"

- name: Installing python dependencies
  command: poetry install --no-dev --no-interaction
  args:
    chdir: "{{ repo_dir }}/django"
  become: yes
  become_user: "{{ app_user }}"

- name: Migrating database
  command: poetry run python manage.py migrate
  args:
    chdir: "{{ repo_dir }}/django/djangoquickstart"
  become: yes
  become_user: "{{ app_user }}"
  environment:
    DJANGO_SETTINGS_MODULE: "settings.staging"

- name: Installing psutil for checking uWSGI pids
  pip:
    name: psutil
    executable: /usr/bin/pip3

- name: Getting uWSGI server pids
  pids:
    name: uwsgi
  register: uwsgi_pids

- name: Killing uWSGI server
  command: "pkill -INT uwsgi"
  when: uwsgi_pids.pids|length > 0

- name: uWSGI server stopped
  assert:
    that: uwsgi_pids.pids|length == 0

- name: Starting uWSGI server
  command: "poetry run uwsgi uwsgi.ini --daemonize {{ repo_dir }}/django/uwsgi.log"
  args:
    chdir: "{{ repo_dir }}/django"
  become: yes
  become_user: "{{ app_user }}"
  environment:
    APP_DIR: "{{ repo_dir }}/django"
    DJANGO_SETTINGS_MODULE: "settings.staging"

- name: Restarting nginx
  systemd:
    name: nginx
    state: restarted