- name: Install python3
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python3-pip
      - python3-dev
      - python3-pkg-resources
      - python3-setuptools
      - python3-venv